### ISSUE TITLE
Serious need for an update

### ISSUE THREAD

**Issue by Kfelts** [Kludex/awesome-fastapi-projects#15]
I think this is a fantastic collection of projects. Problem is that many links lead to a 404 and a lot of projects have been abandoned for a while. With all of the changes in Python and other dependencies, these examples are dated and a lot of builds fail. Maybe get a group of people willing to check out projects and accept pull requests? I know I'd be willing to contribute.

**Comment by Kludex** [comment]
Hi @Kfelts 👋 

I'm willing to give maintainer rights to whoever wants, but I don't think the idea of this repository was never to be a curated list of FastAPI projects. It was mainly to run a cronjob every day to fetch repositories from GitHub, clone them and list the dependencies.

Would you like to maintain the project following that idea?

**Comment by Kludex** [comment]
Closing this in favor of https://github.com/Kludex/awesome-fastapi-projects/issues/16.

Thanks @berhanu-tarekegn , please read the discussion on that PR. 🙏

**Comment by mahimairaja** [comment]
Hi @Kludex 

I would love to join the maintainers team 👍🏻
