### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Snailedlt** [Kludex/awesome-fastapi-projects#21]
As it stands it's really hard to figure out how to contribute to this project. 

@Kludex if you're not able to maintain this project anymore, a good idea would be to add a `CONTRIBUTING.md` file as a last effort, so that potential maintainer candidates know what maintaining and contributing to the project entails. It'll probably lead to more interest which is good, cause it would be a shame if this project died completely

**Comment by Kludex** [comment]
Hmm... I've added the following note on the README:

<img width="879" alt="Screenshot 2023-07-04 at 21 29 20" src="https://github.com/Kludex/awesome-fastapi-projects/assets/7353520/3b95f20a-f641-4d4d-beea-c27fa2bfd69f">

https://github.com/Kludex/awesome-fastapi-projects/issues/16
